---
title: "E3Task"
author: 'Author: Yelu He'
date: "2023-05-10"
output: html_document
---
## Library preparation
```{r setup, echo = FALSE, warning=FALSE, message=FALSE}
## Prepare the library for further use
library(readr)
library(dplyr)
library(ggplot2)
library(sf)
library(terra)
library(lubridate)
library(zoo)
library(ggpubr)
library(SimilarityMeasures)

```

## Task 0: Import data and preparation
```{r task0, echo = TRUE, warning = FALSE, message = FALSE}
## Load the data
wildschwein <- read_delim("wildschwein_BE_2056.csv", ",")

## select data of sabi in a specific time range
sabi <- wildschwein %>%
    filter(TierName == "Sabi", DatetimeUTC >= "2015-07-01", DatetimeUTC < "2015-07-03")

## View the map of sabi
sabi_sf <- st_as_sf(sabi, coords = c("E", "N"), crs = 2056, remove = FALSE)
ggplot(sabi_sf, aes(x = sabi_sf$E, 
                    y = sabi$N)) + 
  geom_point() + 
  geom_path()

## Specify a temporal window
## Measure distance from every point to every other point within the temporal window
sabi <- sabi %>%
  mutate(
        nMinus2 = sqrt((lag(E, 2) - E)^2 + (lag(N, 2) - N)^2), # distance to pos -30 minutes
        nMinus1 = sqrt((lag(E, 1) - E)^2 + (lag(N, 1) - N)^2), # distance to pos -15 minutes
        nPlus1  = sqrt((E - lead(E, 1))^2 + (N - lead(N, 1))^2), # distance to pos +15 mintues
        nPlus2  = sqrt((E - lead(E, 2))^2 + (N - lead(N, 2))^2) # distance to pos +30 minutes
    )
sabi <- sabi |>
    rowwise() |>
    mutate(
        stepMean = mean(c(nMinus2, nMinus1, nPlus1, nPlus2))
    ) |>
    ungroup()
sabi

## Remove static points
sabi <- sabi |>
    ungroup() |>
    mutate(static = stepMean < mean(stepMean, na.rm = TRUE))

sabi_filter <- sabi |>
    filter(!static)

sabi_filter |>
    ggplot(aes(E, N)) +
    geom_path() +
    geom_point() +
    coord_fixed() +
    theme(legend.position = "bottom")

# Preparation
## Load the data
move0 <- read_delim("movementdata/yelu_dataset_01.csv", ";")
## Use right coordinate system and preserve original E/N columns
move0 <- st_as_sf(move0, coords = c("Longitude", "Latitude"), crs = 2056, remove = FALSE)
## Select needed columns
move1 <- select(move0, Date, Time, Latitude, Longitude, geometry)
head(move1)
move1_coordinates <- st_coordinates(move1)
move1 <- cbind(move1, move1_coordinates)
move1f <- move1[move1$Date == '25.04.2023',]

```


## Task 1: Segmentation
```{r task1, echo = TRUE, warning = FALSE, message = FALSE}
## View the map of records
ggplot(move1f, 
       aes(x = move1f$X, 
           y = move1f$Y)) +
  geom_point() +
  geom_path()

## Specify a temporal window
## Measure distance from every point to every other point within the temporal window
move1f <- move1f %>%
  mutate(
        nMinus2 = sqrt((lag(X, 2) - X)^2 + (lag(Y, 2) - Y)^2), # distance to pos -30 minutes
        nMinus1 = sqrt((lag(X, 1) - X)^2 + (lag(Y, 1) - Y)^2), # distance to pos -15 minutes
        nPlus1  = sqrt((X - lead(X, 1))^2 + (Y - lead(Y, 1))^2), # distance to pos +15 mintues
        nPlus2  = sqrt((X - lead(X, 2))^2 + (Y - lead(Y, 2))^2) # distance to pos +30 minutes
    )


move1f <- move1f %>%
    rowwise() %>%
    mutate(
        stepMean = mean(c(nMinus2, nMinus1, nPlus1, nPlus2))
    ) %>%
    ungroup()
move1f

## Remove static points
move1f <- move1f |>
    ungroup() |>
    mutate(static = stepMean < mean(stepMean, na.rm = TRUE))

move1f_filter <- move1f %>%
    filter(!static)

ggplot(data = move1f_filter, aes(X, Y)) +
    geom_path() +
    geom_point() +
    # coord_fixed() +
    theme(legend.position = "bottom")

```

## Task 2: Specify and apply threshold d
```{r task2, echo = TRUE, warning = FALSE, message = FALSE}
## Explore the value of stepMean
hist(move1f$stepMean)
boxplot(move1f$stepMean)
summary(move1f$stepMean)
## Use the mean of stepMean values as threshold
d <- mean(move1f$stepMean)
## Set to static column
# move1f <- move1f |>
#     ungroup() |>
#     mutate(static = stepMean < mean(stepMean,
#           na.rm = TRUE))


```

## Task 3: Visualize segmented trajectories
```{r task3, echo = TRUE, warning = FALSE, message = FALSE}
ggplot(data = move1f, aes(X, Y, color = static)) +
    geom_path() +
    geom_point() +
    # coord_equal() +
    theme(legend.position = "right")
```

## Task 4: Segment-based analysis
```{r task4, echo = TRUE, warning = FALSE, message = FALSE}
## Assign segment ID for each segment
rle_id <- function(vec) {
    x <- rle(vec)$lengths
    as.factor(rep(seq_along(x), times = x))
}
## Name it _f1 as _filter1, different from _filter
move1f_f1 <- move1f |>
    mutate(segment_id = rle_id(static))
head(move1f_f1)
## Plot the segments based on segment ID
ggplot(data = move1f_f1, aes(X, Y, color = segment_id)) +
    geom_path() +
    geom_point() + 
    # coord_equal() +
    theme(legend.position = "right", legend.key.size = unit(0.5,'cm'), legend.text = element_text(size = 5))
## Calculate the duration time for each segment
move1f_f1 <- move1f_f1 %>% group_by(segment_id) %>% mutate(duration = max(Time) - min(Time))
## Select the segments which has a duration more than five minutes
move1f_f1_5min <- move1f_f1[move1f_f1$duration >= 300,]
unique(move1f_f1_5min$segment_id)
unique(move1f_f1_5min$duration)

## Plot the segments which has a duration more than 5 minutes
ggplot(data = move1f_f1_5min, aes(X, Y, color = segment_id)) +
    geom_path() +
    geom_point() + 
    # coord_equal() +
    theme(legend.position = "right")

## Plot each segment
idlist <- unique(move1f_f1_5min$segment_id)
move1f_f1_5min_1 <- move1f_f1_5min[move1f_f1_5min$segment_id == idlist[1],]
ggplot(data = move1f_f1_5min_1, aes(X, Y)) +
    geom_path() +
    geom_point() +
    ggtitle("segment id = 11")

move1f_f1_5min_2 <- move1f_f1_5min[move1f_f1_5min$segment_id == idlist[2],]
ggplot(data = move1f_f1_5min_2, aes(X, Y)) +
    geom_path() +
    geom_point() +
    ggtitle("segment id = 27")

move1f_f1_5min_3 <- move1f_f1_5min[move1f_f1_5min$segment_id == idlist[3],]
ggplot(data = move1f_f1_5min_3, aes(X, Y)) +
    geom_path() +
    geom_point() +
    ggtitle("segment id = 30")

move1f_f1_5min_4 <- move1f_f1_5min[move1f_f1_5min$segment_id == idlist[4],]
ggplot(data = move1f_f1_5min_4, aes(X, Y)) +
    geom_path() +
    geom_point() +
    ggtitle("segment id = 52")

move1f_f1_5min_5 <- move1f_f1_5min[move1f_f1_5min$segment_id == idlist[5],]
ggplot(data = move1f_f1_5min_5, aes(X, Y)) +
    geom_path() +
    geom_point() +
    ggtitle("segment id = 62")

move1f_f1_5min_6 <- move1f_f1_5min[move1f_f1_5min$segment_id == idlist[6],]
ggplot(data = move1f_f1_5min_6, aes(X, Y)) +
    geom_path() +
    geom_point() +
    ggtitle("segment id = 73")

```

## Task 5: Similarity measures
```{r task5, echo = TRUE, warning = FALSE, message = FALSE}
## Load the data
pedestrian <- read_delim("pedestrian.csv", ",")
pedestrian <- st_as_sf(pedestrian, 
                       coords = c("E", "N"),
                       crs = 2056, 
                       remove = FALSE)
ggplot(pedestrian, 
       aes(x = pedestrian$E, 
           y = pedestrian$N)) + 
  geom_point() + 
  geom_path()

ped1 <- pedestrian[pedestrian$TrajID == '1',]
ped2 <- pedestrian[pedestrian$TrajID == '2',]
ped3 <- pedestrian[pedestrian$TrajID == '3',]
ped4 <- pedestrian[pedestrian$TrajID == '4',]
ped5 <- pedestrian[pedestrian$TrajID == '5',]
ped6 <- pedestrian[pedestrian$TrajID == '6',]

pped1 <- ggplot(ped1, 
                aes(x = ped1$E, y = ped1$N)) +
  geom_point() + 
  geom_path()
pped2 <- ggplot(ped2, 
                aes(x = ped2$E, y = ped2$N)) +
  geom_point() + 
  geom_path()
pped3 <- ggplot(ped3, 
                aes(x = ped3$E, y = ped3$N)) +
  geom_point() + 
  geom_path()
pped4 <- ggplot(ped4, 
                aes(x = ped4$E, y = ped4$N)) +
  geom_point() + 
  geom_path()
pped5 <- ggplot(ped5, 
                aes(x = ped5$E, y = ped5$N)) +
  geom_point() + 
  geom_path()
pped6 <- ggplot(ped6, 
                aes(x = ped6$E, y = ped6$N)) +
  geom_point() + 
  geom_path()

ggarrange(pped1, pped2, pped3, 
          pped4, pped5, pped6,
          ncol = 2, nrow = 3)

```


## Task 6: Calculate similarity
```{r task6, echo = TRUE, warning = FALSE, message = FALSE}
# install.packages("SimilarityMeasures")
# library(SimilarityMeasures)

## Before calculating similarity measures, I think trajectory 1 and 6 are the most similar pairs.

# Convert pedestrian data for each trajectory as matrix
p1 <- data.matrix(data.frame(ped1$E, ped1$N))
p2 <- data.matrix(data.frame(ped2$E, ped2$N))
p3 <- data.matrix(data.frame(ped3$E, ped3$N))
p4 <- data.matrix(data.frame(ped4$E, ped4$N))
p5 <- data.matrix(data.frame(ped5$E, ped5$N))
p6 <- data.matrix(data.frame(ped6$E, ped6$N))

# Similarity measures: DTW
sm_dtw <- c()
sm_dtw[1] <- DTW(p1, p2, pointSpacing = 1)
sm_dtw[2] <- DTW(p1, p3, pointSpacing = 1)
sm_dtw[3] <- DTW(p1, p4, pointSpacing = 1)
sm_dtw[4] <- DTW(p1, p5, pointSpacing = 1)
sm_dtw[5] <- DTW(p1, p6, pointSpacing = 1)
names <- as.character(c(2:6))
sm_dtw_df <- data.frame(cbind(names, sm_dtw))
sm_dtw_df
p_dtw <- ggplot(sm_dtw_df, aes(x=names, y = sm_dtw, fill = names)) +  
  geom_bar(stat = "identity") +
  ggtitle("DTW") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("2" = "coral", 
                               "3" = "lavender",
                               "4" = "skyblue",
                               "5" = "khaki",
                               "6" = "seagreen3"))
# Similarity measures: EditDist
sm_ed <- c()
sm_ed[1] <- EditDist(p1, p2, pointDistance = 15)
sm_ed[2] <- EditDist(p1, p3, pointDistance = 15)
sm_ed[3] <- EditDist(p1, p4, pointDistance = 15)
sm_ed[4] <- EditDist(p1, p5, pointDistance = 15)
sm_ed[5] <- EditDist(p1, p6, pointDistance = 15)
sm_ed
sm_ed_df <- data.frame(cbind(names, sm_ed))
sm_ed_df
p_ed <- ggplot(sm_ed_df, aes(x=names, y = sm_ed, fill = names)) +  
  geom_bar(stat = "identity") +
  ggtitle("EditDist") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("2" = "coral", 
                               "3" = "lavender",
                               "4" = "skyblue",
                               "5" = "khaki",
                               "6" = "seagreen3"))
# Similarity measures: Frechet
sm_fr <- c()
sm_fr[1] <- Frechet(p1, p2, testLeash = -1)
sm_fr[2] <- Frechet(p1, p3, testLeash = -1)
sm_fr[3] <- Frechet(p1, p4, testLeash = -1)
sm_fr[4] <- Frechet(p1, p5, testLeash = -1)
sm_fr[5] <- Frechet(p1, p6, testLeash = -1)
sm_fr
sm_fr_df <- data.frame(cbind(names, sm_fr))
sm_fr_df
sm_fr_df$sm_fr <- round(as.numeric(sm_fr_df$sm_fr), digits = 2)
p_fr <- ggplot(sm_fr_df, aes(x=names, y = sm_fr, fill = names)) +  
  geom_bar(stat = "identity") +
  ggtitle("Frechet") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("2" = "coral", 
                               "3" = "lavender",
                               "4" = "skyblue",
                               "5" = "khaki",
                               "6" = "seagreen3"))
# Similarity measures: LCSS
sm_lc <- c()
sm_lc[1] <- LCSS(p1, p2, pointSpacing = 1,
                pointDistance = 20,
                errorMarg = 2, 
                returnTrans = FALSE)
sm_lc[2] <- LCSS(p1, p3, pointSpacing = 1,
                pointDistance = 20,
                errorMarg = 2, 
                returnTrans = FALSE)
sm_lc[3] <- LCSS(p1, p4, pointSpacing = 1,
                pointDistance = 20,
                errorMarg = 2, 
                returnTrans = FALSE)
sm_lc[4] <- LCSS(p1, p5, pointSpacing = 1,
                pointDistance = 20,
                errorMarg = 2, 
                returnTrans = FALSE)
sm_lc[5] <- LCSS(p1, p6, pointSpacing = 1,
                pointDistance = 20,
                errorMarg = 2, 
                returnTrans = FALSE)
sm_lc
sm_lc_df <- data.frame(cbind(names, sm_lc))
sm_lc_df
p_lc <- ggplot(sm_lc_df, aes(x=names, y = sm_lc, fill = names)) +  
  geom_bar(stat = "identity") +
  ggtitle("LCSS") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = "none") +
  scale_fill_manual(values = c("2" = "coral", 
                               "3" = "lavender",
                               "4" = "skyblue",
                               "5" = "khaki",
                               "6" = "seagreen3"))
ggarrange(p_dtw, p_ed, p_fr, p_lc,
          ncol = 2, nrow = 2)

```

